### ISSUE TITLE
Jetson: Create Wiki tutorial how to flash the Jetson

### ISSUE THREAD

**Issue by Christiaan1990** [tum-phoenix/drive_ml#25]
#### Goal:
Create a wiki totorial how to flash the Jetson

#### Assigments:
- understand how the Jetson should be flashed
- test the procedure
- document results in the TUM-Wiki: [https://wiki.tum.de/display/phoenix/Machine+Learning](url)

#### Assigments:
- for more information, please contact Mykyta

**Comment by MaslinuPoimal** [comment]
Could be a good starting issue.

**Comment by MaslinuPoimal** [comment]
Update:[ Auvidea has not yet provided Jetpack 4.2 availability with the TX2 and seems to be rather unwilling to do so](https://devtalk.nvidia.com/default/topic/1052854/jetpack-4-2-with-auvidea-j90-tx2-carrier-board/). I have contacted them, waiting for response.

**Comment by MaslinuPoimal** [comment]
Response from Auvidea: 

Hi Mykita,

Unfortunately, we haven’t been able to make any progress yet. We are stuck with our test setup; since the J90 doesn’t have HDMI output, we would always use a virtual machine to operate on a J90. However, with Jetpack 4.2, this virtual machine doesn’t work anymore, for some unknown yet reason, and the TX2 gets stuck in an endless reset loop on boot-up. So we are still looking for ways on how to solve this.

Best regards,

Dario

**Comment by MaslinuPoimal** [comment]
I have added a short description about how to perform the process [here](https://wiki.tum.de/display/phoenix/Machine+Learning+Setup) (sub-point "on the car").
